[toolchain]
anchor_version = "1.0.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
rhemify_anchor = "RhemTrceAnch1111111111111111111111111111111"
rhemify_dwallet = "GcGz6uD7FxF6rSjCAU1xBV4ZW1E9EFDa4JA5yPKv1cdL"

[programs.localnet]
rhemify_anchor = "AnNz2XESvXbyt2uNnFaZD3Wr6qZpmHC4iuHzmcxMoPRg"
rhemify_dwallet = "GcGz6uD7FxF6rSjCAU1xBV4ZW1E9EFDa4JA5yPKv1cdL"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"

[hooks]
