[toolchain]
anchor_version = "1.0.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
rhemify_anchor = "HYWjBbLMEz98KnppVkUnHmkUZ4pyQ8abaDRTtUedUkxV"
rhemify_dwallet = "GPgdzfwQ4qG1QcqePY3uR6Uo8SvCwqxRYg7oDsXd5opc"

[programs.localnet]
rhemify_anchor = "HYWjBbLMEz98KnppVkUnHmkUZ4pyQ8abaDRTtUedUkxV"
rhemify_dwallet = "GPgdzfwQ4qG1QcqePY3uR6Uo8SvCwqxRYg7oDsXd5opc"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"

[hooks]
