/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as DashboardWalletsRouteImport } from './routes/dashboard/wallets'
import { Route as DashboardPoliciesRouteImport } from './routes/dashboard/policies'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard/approvals'
import { Route as OnboardingSignupRouteImport } from './routes/_onboarding/signup'
import { Route as OnboardingFundRouteImport } from './routes/_onboarding/fund'
import { Route as OnboardingDeployRouteImport } from './routes/_onboarding/deploy'
import { Route as OnboardingBuildRouteImport } from './routes/_onboarding/build'
import { Route as DashboardAgentAgentIdRouteImport } from './routes/dashboard/agent.$agentId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const DashboardWalletsRoute = DashboardWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPoliciesRoute = DashboardPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRoute,
} as any)
const OnboardingSignupRoute = OnboardingSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingFundRoute = OnboardingFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingDeployRoute = OnboardingDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingBuildRoute = OnboardingBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => OnboardingRoute,
} as any)
const DashboardAgentAgentIdRoute = DashboardAgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/build': typeof OnboardingBuildRoute
  '/deploy': typeof OnboardingDeployRoute
  '/fund': typeof OnboardingFundRoute
  '/signup': typeof OnboardingSignupRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/agent/$agentId': typeof DashboardAgentAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/login': typeof LoginRoute
  '/build': typeof OnboardingBuildRoute
  '/deploy': typeof OnboardingDeployRoute
  '/fund': typeof OnboardingFundRoute
  '/signup': typeof OnboardingSignupRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/agent/$agentId': typeof DashboardAgentAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_onboarding/build': typeof OnboardingBuildRoute
  '/_onboarding/deploy': typeof OnboardingDeployRoute
  '/_onboarding/fund': typeof OnboardingFundRoute
  '/_onboarding/signup': typeof OnboardingSignupRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/agent/$agentId': typeof DashboardAgentAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/build'
    | '/deploy'
    | '/fund'
    | '/signup'
    | '/dashboard/approvals'
    | '/dashboard/policies'
    | '/dashboard/wallets'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/agent/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/build'
    | '/deploy'
    | '/fund'
    | '/signup'
    | '/dashboard/approvals'
    | '/dashboard/policies'
    | '/dashboard/wallets'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/agent/$agentId'
  id:
    | '__root__'
    | '/_marketing'
    | '/_onboarding'
    | '/dashboard'
    | '/login'
    | '/_onboarding/build'
    | '/_onboarding/deploy'
    | '/_onboarding/fund'
    | '/_onboarding/signup'
    | '/dashboard/approvals'
    | '/dashboard/policies'
    | '/dashboard/wallets'
    | '/_marketing/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/agent/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/dashboard/wallets': {
      id: '/dashboard/wallets'
      path: '/wallets'
      fullPath: '/dashboard/wallets'
      preLoaderRoute: typeof DashboardWalletsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/policies': {
      id: '/dashboard/policies'
      path: '/policies'
      fullPath: '/dashboard/policies'
      preLoaderRoute: typeof DashboardPoliciesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_onboarding/signup': {
      id: '/_onboarding/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof OnboardingSignupRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/fund': {
      id: '/_onboarding/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof OnboardingFundRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/deploy': {
      id: '/_onboarding/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof OnboardingDeployRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/build': {
      id: '/_onboarding/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof OnboardingBuildRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/dashboard/agent/$agentId': {
      id: '/dashboard/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/dashboard/agent/$agentId'
      preLoaderRoute: typeof DashboardAgentAgentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingBuildRoute: typeof OnboardingBuildRoute
  OnboardingDeployRoute: typeof OnboardingDeployRoute
  OnboardingFundRoute: typeof OnboardingFundRoute
  OnboardingSignupRoute: typeof OnboardingSignupRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingBuildRoute: OnboardingBuildRoute,
  OnboardingDeployRoute: OnboardingDeployRoute,
  OnboardingFundRoute: OnboardingFundRoute,
  OnboardingSignupRoute: OnboardingSignupRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface DashboardRouteChildren {
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardPoliciesRoute: typeof DashboardPoliciesRoute
  DashboardWalletsRoute: typeof DashboardWalletsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAgentAgentIdRoute: typeof DashboardAgentAgentIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardPoliciesRoute: DashboardPoliciesRoute,
  DashboardWalletsRoute: DashboardWalletsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAgentAgentIdRoute: DashboardAgentAgentIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
